/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminincomyRouteRouteImport } from './routes/adminincomy/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EduIndexRouteImport } from './routes/edu/index'
import { Route as EduLoginRouteImport } from './routes/edu/login'
import { Route as AdminincomyLoginRouteImport } from './routes/adminincomy/login'
import { Route as AdminincomyLeadsRouteImport } from './routes/adminincomy/leads'
import { Route as AdminincomyHeroRouteImport } from './routes/adminincomy/hero'
import { Route as AdminincomyDashboardRouteImport } from './routes/adminincomy/dashboard'
import { Route as AdminincomyLayoutRouteImport } from './routes/adminincomy/_layout'
import { Route as EduProfessorRouteRouteImport } from './routes/edu/professor/route'
import { Route as EduCoordenadorRouteRouteImport } from './routes/edu/coordenador/route'
import { Route as EduAlunoRouteRouteImport } from './routes/edu/aluno/route'
import { Route as EduProfessorIndexRouteImport } from './routes/edu/professor/index'
import { Route as EduCoordenadorIndexRouteImport } from './routes/edu/coordenador/index'
import { Route as EduAlunoIndexRouteImport } from './routes/edu/aluno/index'
import { Route as EduProfessorTurmasRouteImport } from './routes/edu/professor/turmas'
import { Route as EduProfessorRastreamentoRouteImport } from './routes/edu/professor/rastreamento'
import { Route as EduProfessorNotasRouteImport } from './routes/edu/professor/notas'
import { Route as EduProfessorEadRouteImport } from './routes/edu/professor/ead'
import { Route as EduProfessorComunicadosRouteImport } from './routes/edu/professor/comunicados'
import { Route as EduProfessorChamadaRouteImport } from './routes/edu/professor/chamada'
import { Route as EduProfessorAtividadesRouteImport } from './routes/edu/professor/atividades'
import { Route as EduProfessorLayoutRouteImport } from './routes/edu/professor/_layout'
import { Route as EduCoordenadorTurmasRouteImport } from './routes/edu/coordenador/turmas'
import { Route as EduCoordenadorRelatoriosRouteImport } from './routes/edu/coordenador/relatorios'
import { Route as EduCoordenadorProfessoresRouteImport } from './routes/edu/coordenador/professores'
import { Route as EduCoordenadorHorariosRouteImport } from './routes/edu/coordenador/horarios'
import { Route as EduCoordenadorConfiguracoesRouteImport } from './routes/edu/coordenador/configuracoes'
import { Route as EduCoordenadorLayoutRouteImport } from './routes/edu/coordenador/_layout'
import { Route as EduAlunoNotificacoesRouteImport } from './routes/edu/aluno/notificacoes'
import { Route as EduAlunoIaRouteImport } from './routes/edu/aluno/ia'
import { Route as EduAlunoFrequenciaRouteImport } from './routes/edu/aluno/frequencia'
import { Route as EduAlunoEadRouteImport } from './routes/edu/aluno/ead'
import { Route as EduAlunoBoletimRouteImport } from './routes/edu/aluno/boletim'
import { Route as EduAlunoAtividadesRouteImport } from './routes/edu/aluno/atividades'
import { Route as EduAlunoAgendaRouteImport } from './routes/edu/aluno/agenda'
import { Route as EduAlunoLayoutRouteImport } from './routes/edu/aluno/_layout'

const AdminincomyRouteRoute = AdminincomyRouteRouteImport.update({
  id: '/adminincomy',
  path: '/adminincomy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EduIndexRoute = EduIndexRouteImport.update({
  id: '/edu/',
  path: '/edu/',
  getParentRoute: () => rootRouteImport,
} as any)
const EduLoginRoute = EduLoginRouteImport.update({
  id: '/edu/login',
  path: '/edu/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminincomyLoginRoute = AdminincomyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminincomyRouteRoute,
} as any)
const AdminincomyLeadsRoute = AdminincomyLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminincomyRouteRoute,
} as any)
const AdminincomyHeroRoute = AdminincomyHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminincomyRouteRoute,
} as any)
const AdminincomyDashboardRoute = AdminincomyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminincomyRouteRoute,
} as any)
const AdminincomyLayoutRoute = AdminincomyLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminincomyRouteRoute,
} as any)
const EduProfessorRouteRoute = EduProfessorRouteRouteImport.update({
  id: '/edu/professor',
  path: '/edu/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const EduCoordenadorRouteRoute = EduCoordenadorRouteRouteImport.update({
  id: '/edu/coordenador',
  path: '/edu/coordenador',
  getParentRoute: () => rootRouteImport,
} as any)
const EduAlunoRouteRoute = EduAlunoRouteRouteImport.update({
  id: '/edu/aluno',
  path: '/edu/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const EduProfessorIndexRoute = EduProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduCoordenadorIndexRoute = EduCoordenadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EduCoordenadorRouteRoute,
} as any)
const EduAlunoIndexRoute = EduAlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduProfessorTurmasRoute = EduProfessorTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduProfessorRastreamentoRoute =
  EduProfessorRastreamentoRouteImport.update({
    id: '/rastreamento',
    path: '/rastreamento',
    getParentRoute: () => EduProfessorRouteRoute,
  } as any)
const EduProfessorNotasRoute = EduProfessorNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduProfessorEadRoute = EduProfessorEadRouteImport.update({
  id: '/ead',
  path: '/ead',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduProfessorComunicadosRoute = EduProfessorComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduProfessorChamadaRoute = EduProfessorChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduProfessorAtividadesRoute = EduProfessorAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduProfessorLayoutRoute = EduProfessorLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => EduProfessorRouteRoute,
} as any)
const EduCoordenadorTurmasRoute = EduCoordenadorTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => EduCoordenadorRouteRoute,
} as any)
const EduCoordenadorRelatoriosRoute =
  EduCoordenadorRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => EduCoordenadorRouteRoute,
  } as any)
const EduCoordenadorProfessoresRoute =
  EduCoordenadorProfessoresRouteImport.update({
    id: '/professores',
    path: '/professores',
    getParentRoute: () => EduCoordenadorRouteRoute,
  } as any)
const EduCoordenadorHorariosRoute = EduCoordenadorHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => EduCoordenadorRouteRoute,
} as any)
const EduCoordenadorConfiguracoesRoute =
  EduCoordenadorConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => EduCoordenadorRouteRoute,
  } as any)
const EduCoordenadorLayoutRoute = EduCoordenadorLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => EduCoordenadorRouteRoute,
} as any)
const EduAlunoNotificacoesRoute = EduAlunoNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduAlunoIaRoute = EduAlunoIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduAlunoFrequenciaRoute = EduAlunoFrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduAlunoEadRoute = EduAlunoEadRouteImport.update({
  id: '/ead',
  path: '/ead',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduAlunoBoletimRoute = EduAlunoBoletimRouteImport.update({
  id: '/boletim',
  path: '/boletim',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduAlunoAtividadesRoute = EduAlunoAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduAlunoAgendaRoute = EduAlunoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)
const EduAlunoLayoutRoute = EduAlunoLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => EduAlunoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminincomy': typeof AdminincomyRouteRouteWithChildren
  '/edu/aluno': typeof EduAlunoRouteRouteWithChildren
  '/edu/coordenador': typeof EduCoordenadorRouteRouteWithChildren
  '/edu/professor': typeof EduProfessorRouteRouteWithChildren
  '/adminincomy/dashboard': typeof AdminincomyDashboardRoute
  '/adminincomy/hero': typeof AdminincomyHeroRoute
  '/adminincomy/leads': typeof AdminincomyLeadsRoute
  '/adminincomy/login': typeof AdminincomyLoginRoute
  '/edu/login': typeof EduLoginRoute
  '/edu/': typeof EduIndexRoute
  '/edu/aluno/agenda': typeof EduAlunoAgendaRoute
  '/edu/aluno/atividades': typeof EduAlunoAtividadesRoute
  '/edu/aluno/boletim': typeof EduAlunoBoletimRoute
  '/edu/aluno/ead': typeof EduAlunoEadRoute
  '/edu/aluno/frequencia': typeof EduAlunoFrequenciaRoute
  '/edu/aluno/ia': typeof EduAlunoIaRoute
  '/edu/aluno/notificacoes': typeof EduAlunoNotificacoesRoute
  '/edu/coordenador/configuracoes': typeof EduCoordenadorConfiguracoesRoute
  '/edu/coordenador/horarios': typeof EduCoordenadorHorariosRoute
  '/edu/coordenador/professores': typeof EduCoordenadorProfessoresRoute
  '/edu/coordenador/relatorios': typeof EduCoordenadorRelatoriosRoute
  '/edu/coordenador/turmas': typeof EduCoordenadorTurmasRoute
  '/edu/professor/atividades': typeof EduProfessorAtividadesRoute
  '/edu/professor/chamada': typeof EduProfessorChamadaRoute
  '/edu/professor/comunicados': typeof EduProfessorComunicadosRoute
  '/edu/professor/ead': typeof EduProfessorEadRoute
  '/edu/professor/notas': typeof EduProfessorNotasRoute
  '/edu/professor/rastreamento': typeof EduProfessorRastreamentoRoute
  '/edu/professor/turmas': typeof EduProfessorTurmasRoute
  '/edu/aluno/': typeof EduAlunoIndexRoute
  '/edu/coordenador/': typeof EduCoordenadorIndexRoute
  '/edu/professor/': typeof EduProfessorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminincomy': typeof AdminincomyRouteRouteWithChildren
  '/adminincomy/dashboard': typeof AdminincomyDashboardRoute
  '/adminincomy/hero': typeof AdminincomyHeroRoute
  '/adminincomy/leads': typeof AdminincomyLeadsRoute
  '/adminincomy/login': typeof AdminincomyLoginRoute
  '/edu/login': typeof EduLoginRoute
  '/edu': typeof EduIndexRoute
  '/edu/aluno': typeof EduAlunoIndexRoute
  '/edu/aluno/agenda': typeof EduAlunoAgendaRoute
  '/edu/aluno/atividades': typeof EduAlunoAtividadesRoute
  '/edu/aluno/boletim': typeof EduAlunoBoletimRoute
  '/edu/aluno/ead': typeof EduAlunoEadRoute
  '/edu/aluno/frequencia': typeof EduAlunoFrequenciaRoute
  '/edu/aluno/ia': typeof EduAlunoIaRoute
  '/edu/aluno/notificacoes': typeof EduAlunoNotificacoesRoute
  '/edu/coordenador': typeof EduCoordenadorIndexRoute
  '/edu/coordenador/configuracoes': typeof EduCoordenadorConfiguracoesRoute
  '/edu/coordenador/horarios': typeof EduCoordenadorHorariosRoute
  '/edu/coordenador/professores': typeof EduCoordenadorProfessoresRoute
  '/edu/coordenador/relatorios': typeof EduCoordenadorRelatoriosRoute
  '/edu/coordenador/turmas': typeof EduCoordenadorTurmasRoute
  '/edu/professor': typeof EduProfessorIndexRoute
  '/edu/professor/atividades': typeof EduProfessorAtividadesRoute
  '/edu/professor/chamada': typeof EduProfessorChamadaRoute
  '/edu/professor/comunicados': typeof EduProfessorComunicadosRoute
  '/edu/professor/ead': typeof EduProfessorEadRoute
  '/edu/professor/notas': typeof EduProfessorNotasRoute
  '/edu/professor/rastreamento': typeof EduProfessorRastreamentoRoute
  '/edu/professor/turmas': typeof EduProfessorTurmasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminincomy': typeof AdminincomyRouteRouteWithChildren
  '/edu/aluno': typeof EduAlunoRouteRouteWithChildren
  '/edu/coordenador': typeof EduCoordenadorRouteRouteWithChildren
  '/edu/professor': typeof EduProfessorRouteRouteWithChildren
  '/adminincomy/_layout': typeof AdminincomyLayoutRoute
  '/adminincomy/dashboard': typeof AdminincomyDashboardRoute
  '/adminincomy/hero': typeof AdminincomyHeroRoute
  '/adminincomy/leads': typeof AdminincomyLeadsRoute
  '/adminincomy/login': typeof AdminincomyLoginRoute
  '/edu/login': typeof EduLoginRoute
  '/edu/': typeof EduIndexRoute
  '/edu/aluno/_layout': typeof EduAlunoLayoutRoute
  '/edu/aluno/agenda': typeof EduAlunoAgendaRoute
  '/edu/aluno/atividades': typeof EduAlunoAtividadesRoute
  '/edu/aluno/boletim': typeof EduAlunoBoletimRoute
  '/edu/aluno/ead': typeof EduAlunoEadRoute
  '/edu/aluno/frequencia': typeof EduAlunoFrequenciaRoute
  '/edu/aluno/ia': typeof EduAlunoIaRoute
  '/edu/aluno/notificacoes': typeof EduAlunoNotificacoesRoute
  '/edu/coordenador/_layout': typeof EduCoordenadorLayoutRoute
  '/edu/coordenador/configuracoes': typeof EduCoordenadorConfiguracoesRoute
  '/edu/coordenador/horarios': typeof EduCoordenadorHorariosRoute
  '/edu/coordenador/professores': typeof EduCoordenadorProfessoresRoute
  '/edu/coordenador/relatorios': typeof EduCoordenadorRelatoriosRoute
  '/edu/coordenador/turmas': typeof EduCoordenadorTurmasRoute
  '/edu/professor/_layout': typeof EduProfessorLayoutRoute
  '/edu/professor/atividades': typeof EduProfessorAtividadesRoute
  '/edu/professor/chamada': typeof EduProfessorChamadaRoute
  '/edu/professor/comunicados': typeof EduProfessorComunicadosRoute
  '/edu/professor/ead': typeof EduProfessorEadRoute
  '/edu/professor/notas': typeof EduProfessorNotasRoute
  '/edu/professor/rastreamento': typeof EduProfessorRastreamentoRoute
  '/edu/professor/turmas': typeof EduProfessorTurmasRoute
  '/edu/aluno/': typeof EduAlunoIndexRoute
  '/edu/coordenador/': typeof EduCoordenadorIndexRoute
  '/edu/professor/': typeof EduProfessorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminincomy'
    | '/edu/aluno'
    | '/edu/coordenador'
    | '/edu/professor'
    | '/adminincomy/dashboard'
    | '/adminincomy/hero'
    | '/adminincomy/leads'
    | '/adminincomy/login'
    | '/edu/login'
    | '/edu/'
    | '/edu/aluno/agenda'
    | '/edu/aluno/atividades'
    | '/edu/aluno/boletim'
    | '/edu/aluno/ead'
    | '/edu/aluno/frequencia'
    | '/edu/aluno/ia'
    | '/edu/aluno/notificacoes'
    | '/edu/coordenador/configuracoes'
    | '/edu/coordenador/horarios'
    | '/edu/coordenador/professores'
    | '/edu/coordenador/relatorios'
    | '/edu/coordenador/turmas'
    | '/edu/professor/atividades'
    | '/edu/professor/chamada'
    | '/edu/professor/comunicados'
    | '/edu/professor/ead'
    | '/edu/professor/notas'
    | '/edu/professor/rastreamento'
    | '/edu/professor/turmas'
    | '/edu/aluno/'
    | '/edu/coordenador/'
    | '/edu/professor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminincomy'
    | '/adminincomy/dashboard'
    | '/adminincomy/hero'
    | '/adminincomy/leads'
    | '/adminincomy/login'
    | '/edu/login'
    | '/edu'
    | '/edu/aluno'
    | '/edu/aluno/agenda'
    | '/edu/aluno/atividades'
    | '/edu/aluno/boletim'
    | '/edu/aluno/ead'
    | '/edu/aluno/frequencia'
    | '/edu/aluno/ia'
    | '/edu/aluno/notificacoes'
    | '/edu/coordenador'
    | '/edu/coordenador/configuracoes'
    | '/edu/coordenador/horarios'
    | '/edu/coordenador/professores'
    | '/edu/coordenador/relatorios'
    | '/edu/coordenador/turmas'
    | '/edu/professor'
    | '/edu/professor/atividades'
    | '/edu/professor/chamada'
    | '/edu/professor/comunicados'
    | '/edu/professor/ead'
    | '/edu/professor/notas'
    | '/edu/professor/rastreamento'
    | '/edu/professor/turmas'
  id:
    | '__root__'
    | '/'
    | '/adminincomy'
    | '/edu/aluno'
    | '/edu/coordenador'
    | '/edu/professor'
    | '/adminincomy/_layout'
    | '/adminincomy/dashboard'
    | '/adminincomy/hero'
    | '/adminincomy/leads'
    | '/adminincomy/login'
    | '/edu/login'
    | '/edu/'
    | '/edu/aluno/_layout'
    | '/edu/aluno/agenda'
    | '/edu/aluno/atividades'
    | '/edu/aluno/boletim'
    | '/edu/aluno/ead'
    | '/edu/aluno/frequencia'
    | '/edu/aluno/ia'
    | '/edu/aluno/notificacoes'
    | '/edu/coordenador/_layout'
    | '/edu/coordenador/configuracoes'
    | '/edu/coordenador/horarios'
    | '/edu/coordenador/professores'
    | '/edu/coordenador/relatorios'
    | '/edu/coordenador/turmas'
    | '/edu/professor/_layout'
    | '/edu/professor/atividades'
    | '/edu/professor/chamada'
    | '/edu/professor/comunicados'
    | '/edu/professor/ead'
    | '/edu/professor/notas'
    | '/edu/professor/rastreamento'
    | '/edu/professor/turmas'
    | '/edu/aluno/'
    | '/edu/coordenador/'
    | '/edu/professor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminincomyRouteRoute: typeof AdminincomyRouteRouteWithChildren
  EduAlunoRouteRoute: typeof EduAlunoRouteRouteWithChildren
  EduCoordenadorRouteRoute: typeof EduCoordenadorRouteRouteWithChildren
  EduProfessorRouteRoute: typeof EduProfessorRouteRouteWithChildren
  EduLoginRoute: typeof EduLoginRoute
  EduIndexRoute: typeof EduIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/adminincomy': {
      id: '/adminincomy'
      path: '/adminincomy'
      fullPath: '/adminincomy'
      preLoaderRoute: typeof AdminincomyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu/': {
      id: '/edu/'
      path: '/edu'
      fullPath: '/edu/'
      preLoaderRoute: typeof EduIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu/login': {
      id: '/edu/login'
      path: '/edu/login'
      fullPath: '/edu/login'
      preLoaderRoute: typeof EduLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminincomy/login': {
      id: '/adminincomy/login'
      path: '/login'
      fullPath: '/adminincomy/login'
      preLoaderRoute: typeof AdminincomyLoginRouteImport
      parentRoute: typeof AdminincomyRouteRoute
    }
    '/adminincomy/leads': {
      id: '/adminincomy/leads'
      path: '/leads'
      fullPath: '/adminincomy/leads'
      preLoaderRoute: typeof AdminincomyLeadsRouteImport
      parentRoute: typeof AdminincomyRouteRoute
    }
    '/adminincomy/hero': {
      id: '/adminincomy/hero'
      path: '/hero'
      fullPath: '/adminincomy/hero'
      preLoaderRoute: typeof AdminincomyHeroRouteImport
      parentRoute: typeof AdminincomyRouteRoute
    }
    '/adminincomy/dashboard': {
      id: '/adminincomy/dashboard'
      path: '/dashboard'
      fullPath: '/adminincomy/dashboard'
      preLoaderRoute: typeof AdminincomyDashboardRouteImport
      parentRoute: typeof AdminincomyRouteRoute
    }
    '/adminincomy/_layout': {
      id: '/adminincomy/_layout'
      path: ''
      fullPath: '/adminincomy'
      preLoaderRoute: typeof AdminincomyLayoutRouteImport
      parentRoute: typeof AdminincomyRouteRoute
    }
    '/edu/professor': {
      id: '/edu/professor'
      path: '/edu/professor'
      fullPath: '/edu/professor'
      preLoaderRoute: typeof EduProfessorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu/coordenador': {
      id: '/edu/coordenador'
      path: '/edu/coordenador'
      fullPath: '/edu/coordenador'
      preLoaderRoute: typeof EduCoordenadorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu/aluno': {
      id: '/edu/aluno'
      path: '/edu/aluno'
      fullPath: '/edu/aluno'
      preLoaderRoute: typeof EduAlunoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu/professor/': {
      id: '/edu/professor/'
      path: '/'
      fullPath: '/edu/professor/'
      preLoaderRoute: typeof EduProfessorIndexRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/coordenador/': {
      id: '/edu/coordenador/'
      path: '/'
      fullPath: '/edu/coordenador/'
      preLoaderRoute: typeof EduCoordenadorIndexRouteImport
      parentRoute: typeof EduCoordenadorRouteRoute
    }
    '/edu/aluno/': {
      id: '/edu/aluno/'
      path: '/'
      fullPath: '/edu/aluno/'
      preLoaderRoute: typeof EduAlunoIndexRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/professor/turmas': {
      id: '/edu/professor/turmas'
      path: '/turmas'
      fullPath: '/edu/professor/turmas'
      preLoaderRoute: typeof EduProfessorTurmasRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/professor/rastreamento': {
      id: '/edu/professor/rastreamento'
      path: '/rastreamento'
      fullPath: '/edu/professor/rastreamento'
      preLoaderRoute: typeof EduProfessorRastreamentoRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/professor/notas': {
      id: '/edu/professor/notas'
      path: '/notas'
      fullPath: '/edu/professor/notas'
      preLoaderRoute: typeof EduProfessorNotasRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/professor/ead': {
      id: '/edu/professor/ead'
      path: '/ead'
      fullPath: '/edu/professor/ead'
      preLoaderRoute: typeof EduProfessorEadRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/professor/comunicados': {
      id: '/edu/professor/comunicados'
      path: '/comunicados'
      fullPath: '/edu/professor/comunicados'
      preLoaderRoute: typeof EduProfessorComunicadosRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/professor/chamada': {
      id: '/edu/professor/chamada'
      path: '/chamada'
      fullPath: '/edu/professor/chamada'
      preLoaderRoute: typeof EduProfessorChamadaRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/professor/atividades': {
      id: '/edu/professor/atividades'
      path: '/atividades'
      fullPath: '/edu/professor/atividades'
      preLoaderRoute: typeof EduProfessorAtividadesRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/professor/_layout': {
      id: '/edu/professor/_layout'
      path: ''
      fullPath: '/edu/professor'
      preLoaderRoute: typeof EduProfessorLayoutRouteImport
      parentRoute: typeof EduProfessorRouteRoute
    }
    '/edu/coordenador/turmas': {
      id: '/edu/coordenador/turmas'
      path: '/turmas'
      fullPath: '/edu/coordenador/turmas'
      preLoaderRoute: typeof EduCoordenadorTurmasRouteImport
      parentRoute: typeof EduCoordenadorRouteRoute
    }
    '/edu/coordenador/relatorios': {
      id: '/edu/coordenador/relatorios'
      path: '/relatorios'
      fullPath: '/edu/coordenador/relatorios'
      preLoaderRoute: typeof EduCoordenadorRelatoriosRouteImport
      parentRoute: typeof EduCoordenadorRouteRoute
    }
    '/edu/coordenador/professores': {
      id: '/edu/coordenador/professores'
      path: '/professores'
      fullPath: '/edu/coordenador/professores'
      preLoaderRoute: typeof EduCoordenadorProfessoresRouteImport
      parentRoute: typeof EduCoordenadorRouteRoute
    }
    '/edu/coordenador/horarios': {
      id: '/edu/coordenador/horarios'
      path: '/horarios'
      fullPath: '/edu/coordenador/horarios'
      preLoaderRoute: typeof EduCoordenadorHorariosRouteImport
      parentRoute: typeof EduCoordenadorRouteRoute
    }
    '/edu/coordenador/configuracoes': {
      id: '/edu/coordenador/configuracoes'
      path: '/configuracoes'
      fullPath: '/edu/coordenador/configuracoes'
      preLoaderRoute: typeof EduCoordenadorConfiguracoesRouteImport
      parentRoute: typeof EduCoordenadorRouteRoute
    }
    '/edu/coordenador/_layout': {
      id: '/edu/coordenador/_layout'
      path: ''
      fullPath: '/edu/coordenador'
      preLoaderRoute: typeof EduCoordenadorLayoutRouteImport
      parentRoute: typeof EduCoordenadorRouteRoute
    }
    '/edu/aluno/notificacoes': {
      id: '/edu/aluno/notificacoes'
      path: '/notificacoes'
      fullPath: '/edu/aluno/notificacoes'
      preLoaderRoute: typeof EduAlunoNotificacoesRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/aluno/ia': {
      id: '/edu/aluno/ia'
      path: '/ia'
      fullPath: '/edu/aluno/ia'
      preLoaderRoute: typeof EduAlunoIaRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/aluno/frequencia': {
      id: '/edu/aluno/frequencia'
      path: '/frequencia'
      fullPath: '/edu/aluno/frequencia'
      preLoaderRoute: typeof EduAlunoFrequenciaRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/aluno/ead': {
      id: '/edu/aluno/ead'
      path: '/ead'
      fullPath: '/edu/aluno/ead'
      preLoaderRoute: typeof EduAlunoEadRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/aluno/boletim': {
      id: '/edu/aluno/boletim'
      path: '/boletim'
      fullPath: '/edu/aluno/boletim'
      preLoaderRoute: typeof EduAlunoBoletimRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/aluno/atividades': {
      id: '/edu/aluno/atividades'
      path: '/atividades'
      fullPath: '/edu/aluno/atividades'
      preLoaderRoute: typeof EduAlunoAtividadesRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/aluno/agenda': {
      id: '/edu/aluno/agenda'
      path: '/agenda'
      fullPath: '/edu/aluno/agenda'
      preLoaderRoute: typeof EduAlunoAgendaRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
    '/edu/aluno/_layout': {
      id: '/edu/aluno/_layout'
      path: ''
      fullPath: '/edu/aluno'
      preLoaderRoute: typeof EduAlunoLayoutRouteImport
      parentRoute: typeof EduAlunoRouteRoute
    }
  }
}

interface AdminincomyRouteRouteChildren {
  AdminincomyLayoutRoute: typeof AdminincomyLayoutRoute
  AdminincomyDashboardRoute: typeof AdminincomyDashboardRoute
  AdminincomyHeroRoute: typeof AdminincomyHeroRoute
  AdminincomyLeadsRoute: typeof AdminincomyLeadsRoute
  AdminincomyLoginRoute: typeof AdminincomyLoginRoute
}

const AdminincomyRouteRouteChildren: AdminincomyRouteRouteChildren = {
  AdminincomyLayoutRoute: AdminincomyLayoutRoute,
  AdminincomyDashboardRoute: AdminincomyDashboardRoute,
  AdminincomyHeroRoute: AdminincomyHeroRoute,
  AdminincomyLeadsRoute: AdminincomyLeadsRoute,
  AdminincomyLoginRoute: AdminincomyLoginRoute,
}

const AdminincomyRouteRouteWithChildren =
  AdminincomyRouteRoute._addFileChildren(AdminincomyRouteRouteChildren)

interface EduAlunoRouteRouteChildren {
  EduAlunoLayoutRoute: typeof EduAlunoLayoutRoute
  EduAlunoAgendaRoute: typeof EduAlunoAgendaRoute
  EduAlunoAtividadesRoute: typeof EduAlunoAtividadesRoute
  EduAlunoBoletimRoute: typeof EduAlunoBoletimRoute
  EduAlunoEadRoute: typeof EduAlunoEadRoute
  EduAlunoFrequenciaRoute: typeof EduAlunoFrequenciaRoute
  EduAlunoIaRoute: typeof EduAlunoIaRoute
  EduAlunoNotificacoesRoute: typeof EduAlunoNotificacoesRoute
  EduAlunoIndexRoute: typeof EduAlunoIndexRoute
}

const EduAlunoRouteRouteChildren: EduAlunoRouteRouteChildren = {
  EduAlunoLayoutRoute: EduAlunoLayoutRoute,
  EduAlunoAgendaRoute: EduAlunoAgendaRoute,
  EduAlunoAtividadesRoute: EduAlunoAtividadesRoute,
  EduAlunoBoletimRoute: EduAlunoBoletimRoute,
  EduAlunoEadRoute: EduAlunoEadRoute,
  EduAlunoFrequenciaRoute: EduAlunoFrequenciaRoute,
  EduAlunoIaRoute: EduAlunoIaRoute,
  EduAlunoNotificacoesRoute: EduAlunoNotificacoesRoute,
  EduAlunoIndexRoute: EduAlunoIndexRoute,
}

const EduAlunoRouteRouteWithChildren = EduAlunoRouteRoute._addFileChildren(
  EduAlunoRouteRouteChildren,
)

interface EduCoordenadorRouteRouteChildren {
  EduCoordenadorLayoutRoute: typeof EduCoordenadorLayoutRoute
  EduCoordenadorConfiguracoesRoute: typeof EduCoordenadorConfiguracoesRoute
  EduCoordenadorHorariosRoute: typeof EduCoordenadorHorariosRoute
  EduCoordenadorProfessoresRoute: typeof EduCoordenadorProfessoresRoute
  EduCoordenadorRelatoriosRoute: typeof EduCoordenadorRelatoriosRoute
  EduCoordenadorTurmasRoute: typeof EduCoordenadorTurmasRoute
  EduCoordenadorIndexRoute: typeof EduCoordenadorIndexRoute
}

const EduCoordenadorRouteRouteChildren: EduCoordenadorRouteRouteChildren = {
  EduCoordenadorLayoutRoute: EduCoordenadorLayoutRoute,
  EduCoordenadorConfiguracoesRoute: EduCoordenadorConfiguracoesRoute,
  EduCoordenadorHorariosRoute: EduCoordenadorHorariosRoute,
  EduCoordenadorProfessoresRoute: EduCoordenadorProfessoresRoute,
  EduCoordenadorRelatoriosRoute: EduCoordenadorRelatoriosRoute,
  EduCoordenadorTurmasRoute: EduCoordenadorTurmasRoute,
  EduCoordenadorIndexRoute: EduCoordenadorIndexRoute,
}

const EduCoordenadorRouteRouteWithChildren =
  EduCoordenadorRouteRoute._addFileChildren(EduCoordenadorRouteRouteChildren)

interface EduProfessorRouteRouteChildren {
  EduProfessorLayoutRoute: typeof EduProfessorLayoutRoute
  EduProfessorAtividadesRoute: typeof EduProfessorAtividadesRoute
  EduProfessorChamadaRoute: typeof EduProfessorChamadaRoute
  EduProfessorComunicadosRoute: typeof EduProfessorComunicadosRoute
  EduProfessorEadRoute: typeof EduProfessorEadRoute
  EduProfessorNotasRoute: typeof EduProfessorNotasRoute
  EduProfessorRastreamentoRoute: typeof EduProfessorRastreamentoRoute
  EduProfessorTurmasRoute: typeof EduProfessorTurmasRoute
  EduProfessorIndexRoute: typeof EduProfessorIndexRoute
}

const EduProfessorRouteRouteChildren: EduProfessorRouteRouteChildren = {
  EduProfessorLayoutRoute: EduProfessorLayoutRoute,
  EduProfessorAtividadesRoute: EduProfessorAtividadesRoute,
  EduProfessorChamadaRoute: EduProfessorChamadaRoute,
  EduProfessorComunicadosRoute: EduProfessorComunicadosRoute,
  EduProfessorEadRoute: EduProfessorEadRoute,
  EduProfessorNotasRoute: EduProfessorNotasRoute,
  EduProfessorRastreamentoRoute: EduProfessorRastreamentoRoute,
  EduProfessorTurmasRoute: EduProfessorTurmasRoute,
  EduProfessorIndexRoute: EduProfessorIndexRoute,
}

const EduProfessorRouteRouteWithChildren =
  EduProfessorRouteRoute._addFileChildren(EduProfessorRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminincomyRouteRoute: AdminincomyRouteRouteWithChildren,
  EduAlunoRouteRoute: EduAlunoRouteRouteWithChildren,
  EduCoordenadorRouteRoute: EduCoordenadorRouteRouteWithChildren,
  EduProfessorRouteRoute: EduProfessorRouteRouteWithChildren,
  EduLoginRoute: EduLoginRoute,
  EduIndexRoute: EduIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
